// 13. TypeScript With Next.js/6. useRef, Forms, Events/components/Form.tsx
"use client";

import { useRef, type FormEvent, useState } from "react";

type formData = {
  name: string;
  email: string;
  password: string;
};

const Form = () => {
  const [submittedData, setSubmittedData] = useState<formData>({
    name: "",
    email: "",
    password: "",
  });

  const name = useRef<HTMLInputElement>(null);
  const email = useRef<HTMLInputElement>(null);
  const password = useRef<HTMLInputElement>(null);

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const nameVal = name.current!.value;
    const emailVal = email.current!.value;
    const passwordVal = password.current!.value;

    setSubmittedData({
      name: nameVal,
      email: emailVal,
      password: passwordVal,
    });

    console.log(nameVal);
    console.log(emailVal);
    console.log(passwordVal);
  };

  return (
    <form onSubmit={handleSubmit}>
      <input type="text" placeholder="Enter your name" ref={name} />
      <input type="email" placeholder="Enter your email" ref={email} />
      <input type="password" placeholder="Enter your password" ref={password} />
      <button type="submit">Submit</button>

      <section>
        <h1>Name: {submittedData.name}</h1>
        <h1>Email: {submittedData.email}</h1>
        <h1>Password: {submittedData.password}</h1>
      </section>
    </form>
  );
};

export default Form;

// 18. Vue.js Complete Course With 10 Projects/14. Forms (v-model)/src/components/FormComponent.vue
<script setup>
import { reactive } from 'vue'
const formData = reactive({ username: '', email: '', password: '' })
</script>

<template>
  <form @submit.prevent="alert('form submitted')">
    <input type="text" placeholder="Please enter your name." v-model="formData.username" />
    <input type="email" placeholder="Please enter your email." v-model="formData.email" />
    <input type="password" placeholder="Please enter your password." v-model="formData.password" />
    <button type="submit">Submit</button>
  </form>

  <h1>{{ formData.username }}</h1>
  <h1>{{ formData.email }}</h1>
  <h1>{{ formData.password }}</h1>
</template>
