// 14. TypeScript With Next.js/5. useState Types/components/Counter.tsx
// import { useState } from "react";

// const Counter = () => {
//   const [count, setCount] = useState<number>(0);

//   const increment = () => {
//     setCount(count + 1);
//   };

//   const decrement = () => {
//     setCount(count - 1);
//   };

//   return (
//     <div>
//       <h1>Counter App</h1>
//       <p>Count: {count}</p>
//       <button onClick={increment}>Increment</button>
//       <button onClick={decrement}>Decrement</button>
//     </div>
//   );
// };

// export default Counter;
// ---------------------------------
"use client";

import { useState } from "react";

const Counter = () => {
  const [count, setCount] = useState<number>(0);

  return (
    <div>
      <h1>Counter App</h1>
      <p>Count: {count}</p>
      <button onClick={() => setCount(count + 1)}>Increment</button>
      <button onClick={() => setCount(count - 1)}>Decrement</button>
    </div>
  );
};

export default Counter;

// 20. Vue.js Complete Course With 10 Projects/23. Composable/src/Example 1/components/CounterComponent.vue
<script setup>
import { useCounter } from './shared/useCounter'
const counter = useCounter()
</script>

<template>
  <div>
    <p>Count: {{ counter.count }}</p>
    <button @click="counter.increment">Increment</button>
    <button @click="counter.decrement">Decrement</button>
  </div>
</template>
../shared/useCounter
