// 20. Vue.js Complete Course With 10 Projects/23. Composable/src/Example 1/components/CounterComponent.vue
<script setup>
import { useCounter } from './shared/useCounter'
const counter = useCounter()
</script>

<template>
  <div>
    <p>Count: {{ counter.count }}</p>
    <button @click="counter.increment">Increment</button>
    <button @click="counter.decrement">Decrement</button>
  </div>
</template>
../shared/useCounter

// 13. TypeScript With Next.js/10. useReducer/components/Counter.tsx
import { useReducer } from "react";

// Define types for state and actions
type State = {
  count: number;
};

type Action = { type: "INCREMENT" } | { type: "DECREMENT" };

// Reducer function with types
const reducer = (state: State, action: Action): State => {
  switch (action.type) {
    case "INCREMENT":
      return { count: state.count + 1 };
    case "DECREMENT":
      return { count: state.count - 1 };
    default:
      return state;
  }
};

const Counter = () => {
  const [state, dispatch] = useReducer(reducer, { count: 0 });

  return (
    <div>
      <p>Count: {state.count}</p>
      <button onClick={() => dispatch({ type: "INCREMENT" })}>Increment</button>
      <button onClick={() => dispatch({ type: "DECREMENT" })}>Decrement</button>
    </div>
  );
};

export default Counter;
